all_questions = [
    ["What is the capital of France?", "Berlin", "Madrid", "Paris", "Lisbon", "c"],
    ["Which planet is known as the Red Planet?", "Earth", "Mars", "Jupiter", "Saturn", "b"],
    ["What is the largest ocean on Earth?", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean", "d"],
    ["Who wrote 'Romeo and Juliet'?", "Charles Dickens", "Mark Twain", "William Shakespeare", "Jane Austen", "c"],
    ["What is the chemical symbol for water?", "H2O", "O2", "CO2", "NaCl", "a"],
    ["Which gas do plants absorb from the atmosphere?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen", "b"],
    ["What is the hardest natural substance on Earth?", "Gold", "Iron", "Diamond", "Quartz", "c"],
    ["Who painted the Mona Lisa?", "Vincent Van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet", "c"],
    ["What is the smallest prime number?", "0", "1", "2", "3", "c"],
    ["Which element has the atomic number 1?", "Helium", "Oxygen", "Hydrogen", "Lithium", "c"],
    ["What is the capital of Japan?", "Seoul", "Beijing", "Tokyo", "Bangkok", "c"],
    ["Which organ is responsible for pumping blood in the human body?", "Liver", "Lungs", "Heart", "Kidneys", "c"],
    ["What is the largest mammal in the world?", "Elephant", "Blue Whale", "Giraffe", "Great White Shark", "b"],
    ["What is the main ingredient in guacamole?", "Tomato", "Avocado", "Pepper", "Onion", "b"],
    ["Which country is known as the Land of the Rising Sun?", "China", "Japan", "Thailand", "South Korea", "b"],
    ["What is the freezing point of water?", "0°C", "32°F", "100°C", "212°F", "a"],
    ["Who discovered penicillin?", "Marie Curie", "Alexander Fleming", "Louis Pasteur", "Isaac Newton", "b"],
    ["What is the capital of Australia?", "Sydney", "Canberra", "Melbourne", "Brisbane", "b"],
    ["Which planet is closest to the Sun?", "Venus", "Earth", "Mercury", "Mars", "c"],
    ["What is the largest continent?", "Africa", "Asia", "North America", "South America", "b"],
    ["What is the currency of the United Kingdom?", "Dollar", "Euro", "Pound Sterling", "Yen", "c"],
    ["Which vitamin is produced when a person is exposed to sunlight?", "Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D", "d"],
    ["What is the capital of Canada?", "Toronto", "Ottawa", "Vancouver", "Montreal", "b"],
    ["Which instrument is used to measure atmospheric pressure?", "Thermometer", "Barometer", "Hygrometer", "Anemometer", "b"],
    ["What is the largest planet in our solar system?", "Earth", "Mars", "Jupiter", "Saturn", "c"],
    ["Who is known as the Father of Geometry?", "Euclid", "Pythagoras", "Archimedes", "Newton", "a"],
    ["What is the main language spoken in Brazil?", "Spanish", "Portuguese", "English", "French", "b"],
    ["Which element is represented by the symbol 'O'?", "Gold", "Oxygen", "Silver", "Iron", "b"],
    ["What is the capital of Italy?", "Rome", "Venice", "Florence", "Milan", "a"],
    ["Which planet is known for its rings?", "Earth", "Mars", "Jupiter", "Saturn", "d"],
    ["What is the largest desert in the world?", "Sahara", "Arabian", "Gobi", "Antarctic", "d"],
    ["Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "F. Scott Fitzgerald", "a"],
    ["What is the boiling point of water?", "100°C", "90°C", "80°C", "70°C", "a"],
    ["Which country is famous for the Great Wall?", "India", "China", "Japan", "Russia", "b"],
    ["What is the capital of Germany?", "Berlin", "Munich", "Frankfurt", "Hamburg", "a"],
    ["Which gas is most abundant in the Earth's atmosphere?", "Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen", "b"],
    ["What is the primary language spoken in Egypt?", "Arabic", "English", "French", "Spanish", "a"],
    ["Which planet is known as the 'Giant Planet'?", "Earth", "Jupiter", "Mars", "Venus", "b"],
    ["What is the capital of Russia?", "Moscow", "St. Petersburg", "Kiev", "Warsaw", "a"],
    ["Who is known for the theory of relativity?", "Isaac Newton", "Albert Einstein", "Galileo Galilei",
     "Stephen Hawking", "b"],
    ["What is the largest organ in the human body?", "Heart", "Liver", "Skin", "Lungs", "c"],
    ["Which element is a noble gas?", "Oxygen", "Nitrogen", "Argon", "Hydrogen", "c"],
    ["What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador", "a"],
    ["Which animal is known as the 'King of the Jungle'?", "Elephant", "Lion", "Tiger", "Bear", "b"],
    ["What is the main ingredient in bread?", "Flour", "Sugar", "Salt", "Water", "a"],
    ["Which planet is known for its Great Red Spot?", "Earth", "Mars", "Jupiter", "Saturn", "c"],
    ["What is the capital of South Africa?", "Cape Town", "Pretoria", "Johannesburg", "Durban", "b"],
    ["Who invented the telephone?", "Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi", "a"],
    ["What is the largest land animal?", "Hippopotamus", "Elephant", "Giraffe", "Rhino", "b"],
    ["Which country is known for the Eiffel Tower?", "Italy", "Germany", "France", "Spain", "c"],
    ["What is the capital of Spain?", "Barcelona", "Madrid", "Seville", "Valencia", "b"],
    ["Which vitamin is known as ascorbic acid?", "Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D", "c"],
    ["What is the main ingredient in sushi?", "Rice", "Fish", "Seaweed", "Vegetables", "a"],
    ["Which ocean is the smallest?", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean", "c"],
    ["What is the capital of Mexico?", "Cancun", "Guadalajara", "Mexico City", "Tijuana", "c"],
    ["Which planet is known for having the most moons?", "Earth", "Mars", "Jupiter", "Saturn", "c"],
    ["What is the chemical symbol for gold?", "Au", "Ag", "Fe", "Pb", "a"],
    ["Who is the author of 'Pride and Prejudice'?", "Charlotte Brontë", "Jane Austen", "Emily Dickinson",
     "Mary Shelley", "b"],
    ["What is the capital of Egypt?", "Cairo", "Alexandria", "Giza", "Luxor", "a"],
    ["Which instrument is used to measure temperature?", "Barometer", "Thermometer", "Hygrometer", "Anemometer", "b"],
    ["What is the largest island in the world?", "Greenland", "New Guinea", "Borneo", "Madagascar", "a"],
    ["Which country is known for the kangaroo?", "South Africa", "Australia", "India", "Canada", "b"],
    ["What is the capital of Italy?", "Rome", "Venice", "Florence", "Milan", "a"],
    ["Which gas is used in balloons?", "Oxygen", "Helium", "Nitrogen", "Carbon Dioxide", "b"],
    ["What is the main language spoken in Argentina?", "Spanish", "Portuguese", "English", "French", "a"]
]
